/**
 * CRUD Operations Test API Route
 * Tests create, read, update, delete operations with authentication
 */

import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { randomUUID } from 'crypto';

export async function GET() {
  try {
    console.log('Testing CRUD operations...');

    // For testing purposes, we'll create a test user ID (valid UUID format)
    // In production, this would come from authentication
    const testUserId = randomUUID();

    // Test 1: Create a journal entry
    const createData = {
      user_id: testUserId,
      title: 'Test Entry',
      content: 'This is a test journal entry created at ' + new Date().toISOString(),
    };

    const { data: createdEntry, error: createError } = await supabase
      .from('journal_entries')
      .insert(createData)
      .select()
      .single();

    if (createError) {
      return NextResponse.json(
        {
          success: false,
          step: 'create',
          error: createError,
        },
        { status: 500 }
      );
    }

    // Test 2: Read the created entry
    const { data: readEntry, error: readError } = await supabase
      .from('journal_entries')
      .select('*')
      .eq('id', createdEntry.id)
      .single();

    if (readError) {
      return NextResponse.json(
        {
          success: false,
          step: 'read',
          error: readError,
        },
        { status: 500 }
      );
    }

    // Test 3: Update the entry
    const { data: updatedEntry, error: updateError } = await supabase
      .from('journal_entries')
      .update({
        title: 'Updated Test Entry',
        content: 'This entry has been updated at ' + new Date().toISOString(),
      })
      .eq('id', createdEntry.id)
      .select()
      .single();

    if (updateError) {
      return NextResponse.json(
        {
          success: false,
          step: 'update',
          error: updateError,
        },
        { status: 500 }
      );
    }

    // Test 4: Create AI analysis for the entry
    const analysisData = {
      journal_entry_id: createdEntry.id,
      summary: 'This is a test summary generated by AI',
      emotions: { joy: 0.7, neutral: 0.3 },
      suggestions: { categories: ['reflection', 'gratitude'] },
      model: 'test-model',
    };

    const { data: createdAnalysis, error: analysisError } = await supabase
      .from('ai_analysis')
      .insert(analysisData)
      .select()
      .single();

    if (analysisError) {
      return NextResponse.json(
        {
          success: false,
          step: 'create_analysis',
          error: analysisError,
        },
        { status: 500 }
      );
    }

    // Test 5: Query the combined view
    const { data: combinedData, error: combinedError } = await supabase
      .from('journal_entries_with_analysis')
      .select('*')
      .eq('id', createdEntry.id)
      .single();

    if (combinedError) {
      return NextResponse.json(
        {
          success: false,
          step: 'combined_view',
          error: combinedError,
        },
        { status: 500 }
      );
    }

    // Test 6: Clean up - Delete the test data
    await supabase.from('ai_analysis').delete().eq('id', createdAnalysis.id);
    await supabase.from('journal_entries').delete().eq('id', createdEntry.id);

    return NextResponse.json({
      success: true,
      message: 'All CRUD operations completed successfully',
      timestamp: new Date().toISOString(),
      results: {
        created: createdEntry,
        read: readEntry,
        updated: updatedEntry,
        analysis: createdAnalysis,
        combined: combinedData,
      },
      note: 'Test data has been cleaned up',
    });
  } catch (error) {
    console.error('CRUD test error:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'CRUD test failed',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
